package com.jcaro.jcstudentapi.application.mapper;

import com.jcaro.jcstudentapi.application.dto.course.CourseRequest;
import com.jcaro.jcstudentapi.domain.model.Course;

import java.util.Collections;

/**
 * Mapper for converting between CourseRequest DTOs and the Course domain model.
 * <p>
 * This class resides in the application layer and ensures separation of concerns by
 * translating data to and from the domain without introducing any Spring dependencies.
 * IDs and relationships (students, assignments) are not handled here and are expected
 * to be managed by persistence or higher-level services.
 */
public class CourseMapper {

    /**
     * Converts a CourseRequest DTO into a Course domain object.
     * <p>
     * The ID is set to {@code null} because it will be generated by the persistence layer.
     * Students and assignments are initialized as {@code null} because they are managed separately.
     *
     * @param dto the CourseRequest DTO containing input data
     * @return a new Course domain object
     */
    public Course requestToDomain(CourseRequest dto) {
        return new Course(
                null,
                dto.name(),
                dto.programmingLanguage(),
                Collections.emptyList(),
                Collections.emptyList(),
                Collections.emptyList()
        );
    }
}
